export enum LoanStatus {
  PENDING = 'PENDING',
  ESCROW_CREATED = 'ESCROW_CREATED',
  VERIFICATION_PENDING = 'VERIFICATION_PENDING',
  QUALIFIED = 'QUALIFIED',
  NOT_QUALIFIED = 'NOT_QUALIFIED',
  FUNDED = 'FUNDED',
  REPAID = 'REPAID',
  DEFAULTED = 'DEFAULTED',
  CANCELED = 'CANCELED',
}
